
Import pandas and numpy, and create a sample dataset

In [1]:
import pandas as pd
import numpy as np

# Sample sales dataset 
data = {
    "OrderID": range(1, 11),
    "Customer": ["Alice", "Bob", "Charlie", "Alice", "Dave", "Bob", "Eve", "Charlie", "Alice", "Dave"],
    "Region": ["East", "West", "East", "East", "South", "West", "North", "East", "West", "South"],
    "Product": ["Widget", "Gadget", "Widget", "Gizmo", "Widget", "Gadget", "Gizmo", "Gadget", "Widget", "Gizmo"],
    "Quantity": [10, 5, 8, 3, np.nan, 7, 12, 4, 6, 9],
    "Price": [2.5, 15.0, 2.5, 7.0, 2.5, 15.0, 7.0, 15.0, 2.5, 7.0],
}
df = pd.DataFrame(data)
df

   OrderID Customer Region Product  Quantity  Price
0        1    Alice   East  Widget      10.0    2.5
1        2      Bob   West  Gadget       5.0   15.0
2        3  Charlie   East  Widget       8.0    2.5
3        4    Alice   East   Gizmo       3.0    7.0
4        5     Dave  South  Widget       NaN    2.5
5        6      Bob   West  Gadget       7.0   15.0
6        7      Eve  North   Gizmo      12.0    7.0
7        8  Charlie   East  Gadget       4.0   15.0
8        9    Alice   West  Widget       6.0    2.5
9       10     Dave  South   Gizmo       9.0    7.0

Pandas is a Python library built on top of NumPy that provides fast, flexible, and expressive data structures for working with structured (tabular) data.

In [2]:
print("Pandas version:", pd.__version__)
print("Built on top of NumPy version:", np.__version__)

Pandas version: 2.3.3
Built on top of NumPy version: 1.26.4


A **Series** is a one-dimensional labeled array capable of holding data of any type; it's the building block of a DataFrame column.

In [3]:
s = pd.Series([100, 200, 300, 400], index=["a", "b", "c", "d"], name="Sales")
print(s)
print("\nType:", type(s))
print("Value at label 'b':", s["b"])

a    100
b    200
c    300
d    400
Name: Sales, dtype: int64

Type: <class 'pandas.core.series.Series'>
Value at label 'b': 200

DataFrame
A **DataFrame** is a two-dimensional, size-mutable, tabular data structure with labeled rows (index) and columns — similar to a spreadsheet or SQL table.

In [4]:
print("Type:", type(df))
print("Columns:", list(df.columns))
print("Index:", df.index.tolist())
df

Type: <class 'pandas.core.frame.DataFrame'>
Columns: ['OrderID', 'Customer', 'Region', 'Product', 'Quantity', 'Price']
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

   OrderID Customer Region Product  Quantity  Price
0        1    Alice   East  Widget      10.0    2.5
1        2      Bob   West  Gadget       5.0   15.0
2        3  Charlie   East  Widget       8.0    2.5
3        4    Alice   East   Gizmo       3.0    7.0
4        5     Dave  South  Widget       NaN    2.5
5        6      Bob   West  Gadget       7.0   15.0
6        7      Eve  North   Gizmo      12.0    7.0
7        8  Charlie   East  Gadget       4.0   15.0
8        9    Alice   West  Widget       6.0    2.5
9       10     Dave  South   Gizmo       9.0    7.0

Data Loading
Functions such as `read_csv()`, `read_excel()`, and `read_json()` load data from external files into a DataFrame.

In [5]:
# Save to CSV, then load it back
df.to_csv("sales.csv", index=False)
df_from_csv = pd.read_csv("sales.csv")

# Save to JSON, then load it back
df.to_json("sales.json", orient="records")
df_from_json = pd.read_json("sales.json")

# read_excel() works the same way once you have an .xlsx file:
# df_from_excel = pd.read_excel("sales.xlsx")

#df_from_csv.head()
df_from_csv.tail()

   OrderID Customer Region Product  Quantity  Price
5        6      Bob   West  Gadget       7.0   15.0
6        7      Eve  North   Gizmo      12.0    7.0
7        8  Charlie   East  Gadget       4.0   15.0
8        9    Alice   West  Widget       6.0    2.5
9       10     Dave  South   Gizmo       9.0    7.0

Data Inspection
`head()`, `tail()`, `info()`, `describe()`, and `shape` give a quick overview of the dataset.

In [6]:
print("First 3 rows:")
display(df.head(3))

print("\nLast 3 rows:")
display(df.tail(3))

print("\nInfo:")
df.info()

print("\nDescribe:")
display(df.describe())

print("\nShape (rows, columns):", df.shape)

First 3 rows:

   OrderID Customer Region Product  Quantity  Price
0        1    Alice   East  Widget      10.0    2.5
1        2      Bob   West  Gadget       5.0   15.0
2        3  Charlie   East  Widget       8.0    2.5

Last 3 rows:

   OrderID Customer Region Product  Quantity  Price
7        8  Charlie   East  Gadget       4.0   15.0
8        9    Alice   West  Widget       6.0    2.5
9       10     Dave  South   Gizmo       9.0    7.0

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   OrderID   10 non-null     int64
 1   Customer  10 non-null     object
 2   Region    10 non-null     object
 3   Product   10 non-null     object
 4   Quantity  9 non-null      float64
 5   Price     10 non-null     float64
dtypes: float64(2), int64(1), object(3)
memory usage: 608.0+ bytes

Describe:

        OrderID   Quantity      Price
count  10.00000   9.000000  10.000000
mean    5.50000   7.111111   7.600000
std     3.02765   2.934469   5.471136
min     1.00000   3.000000   2.500000
25%     3.25000   5.000000   2.500000
50%     5.50000   7.000000   7.000000
75%     7.75000   9.000000  13.000000
max    10.00000  12.000000  15.000000

Shape (rows, columns): (10, 6)

Indexing & Selection
`loc[]` (label-based) and `iloc[]` (position-based) access specific rows/columns; boolean indexing filters rows based on conditions.

In [7]:
# loc: label-based selection
print("loc example (rows 0-2, specific columns):")
display(df.loc[0:2, ["Customer", "Product", "Price"]])

# iloc: position-based selection
print("\niloc example (first 3 rows, first 3 columns):")
display(df.iloc[0:3, 0:3])

# Boolean indexing: filter rows where Region is 'East'
print("\nBoolean indexing (Region == 'East'):")
display(df[df["Region"] == "East"])

loc example (rows 0-2, specific columns):

  Customer Product  Price
0    Alice  Widget    2.5
1      Bob  Gadget   15.0
2  Charlie  Widget    2.5

iloc example (first 3 rows, first 3 columns):

   OrderID Customer Region
0        1    Alice   East
1        2      Bob   West
2        3  Charlie   East

Boolean indexing (Region == 'East'):

   OrderID Customer Region Product  Quantity  Price
0        1    Alice   East  Widget      10.0    2.5
2        3  Charlie   East  Widget       8.0    2.5
3        4    Alice   East   Gizmo       3.0    7.0
7        8  Charlie   East  Gadget       4.0   15.0

Group-By & Aggregation
`groupby()` splits data into groups based on a column, and aggregation functions such as `sum()`, `mean()`, `count()`, and `agg()` summarize each group.

In [8]:
# Total quantity sold per region
print("Sum of Quantity by Region:")
display(df.groupby("Region")["Quantity"].sum())

# Average price per product
print("\nMean Price by Product:")
display(df.groupby("Product")["Price"].mean())

# Multiple aggregations at once with agg()
print("\nMultiple aggregations with agg():")
display(df.groupby("Region").agg(
    total_qty=("Quantity", "sum"),
    avg_price=("Price", "mean"),
    order_count=("OrderID", "count")
))

Sum of Quantity by Region:

Region
East     25.0
North    12.0
South     9.0
West     18.0
Name: Quantity, dtype: float64

Mean Price by Product:

Product
Gadget    15.0
Gizmo      7.0
Widget     2.5
Name: Price, dtype: float64

Multiple aggregations with agg():

        total_qty  avg_price  order_count
Region
East         25.0   6.750000            4
North        12.0   7.000000            1
South         9.0   4.750000            2
West         18.0  10.833333            3

`pivot_table()` reshapes and summarizes data, similar to a spreadsheet pivot table, by grouping and aggregating along rows and columns.

In [9]:
pivot = pd.pivot_table(
    df,
    values="Quantity",
    index="Region",
    columns="Product",
    aggfunc="sum",
    fill_value=0
)
pivot

Product  Gadget  Gizmo  Widget
Region
East        4.0    3.0    18.0
North       0.0   12.0     0.0
South       0.0    9.0     0.0
West       12.0    0.0     6.0

Handling Missing Data
`isnull()`, `dropna()`, and `fillna()` detect and handle missing values in a dataset.

In [10]:
print("Missing values per column:")
display(df.isnull().sum())

print("\nRows with any missing values:")
display(df[df.isnull().any(axis=1)])

print("\nDropping rows with missing values (dropna):")
display(df.dropna())

print("\nFilling missing Quantity with the column mean (fillna):")
df_filled = df.copy()
df_filled["Quantity"] = df_filled["Quantity"].fillna(df_filled["Quantity"].mean())
display(df_filled)

Missing values per column:

OrderID     0
Customer    0
Region      0
Product     0
Quantity    1
Price       0
dtype: int64

Rows with any missing values:

   OrderID Customer Region Product  Quantity  Price
4        5     Dave  South  Widget       NaN    2.5

Dropping rows with missing values (dropna):

   OrderID Customer Region Product  Quantity  Price
0        1    Alice   East  Widget      10.0    2.5
1        2      Bob   West  Gadget       5.0   15.0
2        3  Charlie   East  Widget       8.0    2.5
3        4    Alice   East   Gizmo       3.0    7.0
5        6      Bob   West  Gadget       7.0   15.0
6        7      Eve  North   Gizmo      12.0    7.0
7        8  Charlie   East  Gadget       4.0   15.0
8        9    Alice   West  Widget       6.0    2.5
9       10     Dave  South   Gizmo       9.0    7.0

Filling missing Quantity with the column mean (fillna):

   OrderID Customer Region Product   Quantity  Price
0        1    Alice   East  Widget  10.000000    2.5
1        2      Bob   West  Gadget   5.000000   15.0
2        3  Charlie   East  Widget   8.000000    2.5
3        4    Alice   East   Gizmo   3.000000    7.0
4        5     Dave  South  Widget   7.111111    2.5
5        6      Bob   West  Gadget   7.000000   15.0
6        7      Eve  North   Gizmo  12.000000    7.0
7        8  Charlie   East  Gadget   4.000000   15.0
8        9    Alice   West  Widget   6.000000    2.5
9       10     Dave  South   Gizmo   9.000000    7.0

Data Transformation
`apply()`, `map()`, `astype()`, `rename()`, and `sort_values()` transform, enrich, and reorganize DataFrame columns.

In [11]:
df_t = df_filled.copy()

# apply(): create a new column using a custom function
df_t["Total"] = df_t.apply(lambda row: row["Quantity"] * row["Price"], axis=1)

# map(): map values in a column to new values
region_codes = {"East": "E", "West": "W", "South": "S", "North": "N"}
df_t["RegionCode"] = df_t["Region"].map(region_codes)

# astype(): change a column's data type
df_t["Quantity"] = df_t["Quantity"].astype(int)

# rename(): rename columns
df_t = df_t.rename(columns={"Total": "TotalRevenue"})

# sort_values(): sort rows by a column
df_t = df_t.sort_values(by="TotalRevenue", ascending=False)

df_t

   OrderID Customer Region Product  Quantity  Price  TotalRevenue RegionCode
5        6      Bob   West  Gadget         7   15.0    105.000000          W
6        7      Eve  North   Gizmo        12    7.0     84.000000          N
1        2      Bob   West  Gadget         5   15.0     75.000000          W
9       10     Dave  South   Gizmo         9    7.0     63.000000          S
7        8  Charlie   East  Gadget         4   15.0     60.000000          E
0        1    Alice   East  Widget        10    2.5     25.000000          E
3        4    Alice   East   Gizmo         3    7.0     21.000000          E
2        3  Charlie   East  Widget         8    2.5     20.000000          E
4        5     Dave  South  Widget         7    2.5     17.777778          S
8        9    Alice   West  Widget         6    2.5     15.000000          W

Merging & Joining
`merge()`, `join()`, combine multiple DataFrames based on common keys or indices.

In [12]:
# A second DataFrame with extra customer info, to merge with df
customer_info = pd.DataFrame({
    "Customer": ["Alice", "Bob", "Charlie", "Dave", "Eve"],
    "City": ["New York", "Chicago", "Boston", "Houston", "Miami"],
    "MembershipLevel": ["Gold", "Silver", "Gold", "Bronze", "Silver"]
})

# merge(): SQL-style join on a common column
merged_df = pd.merge(df, customer_info, on="Customer", how="left")
print("merge() result:")
display(merged_df.head())

# join(): join on index (set Customer as index on both first)
joined_df = df.set_index("Customer").join(customer_info.set_index("Customer"), how="left")
print("\njoin() result:")
display(joined_df.head())

# concat(): stack DataFrames together (e.g., two batches of orders)
batch1 = df.iloc[:5]
batch2 = df.iloc[5:]
concatenated_df = pd.concat([batch1, batch2], ignore_index=True)
print("\nconcat() result (recombined batches):")
display(concatenated_df)

merge() result:

   OrderID Customer Region Product  Quantity  Price      City MembershipLevel
0        1    Alice   East  Widget      10.0    2.5  New York            Gold
1        2      Bob   West  Gadget       5.0   15.0   Chicago          Silver
2        3  Charlie   East  Widget       8.0    2.5    Boston            Gold
3        4    Alice   East   Gizmo       3.0    7.0  New York            Gold
4        5     Dave  South  Widget       NaN    2.5   Houston          Bronze

join() result:

          OrderID Region Product  Quantity  Price      City MembershipLevel
Customer
Alice           1   East  Widget      10.0    2.5  New York            Gold
Bob             2   West  Gadget       5.0   15.0   Chicago          Silver
Charlie         3   East  Widget       8.0    2.5    Boston            Gold
Alice           4   East   Gizmo       3.0    7.0  New York            Gold
Dave            5  South  Widget       NaN    2.5   Houston          Bronze

concat() result (recombined batches):

   OrderID Customer Region Product  Quantity  Price
0        1    Alice   East  Widget      10.0    2.5
1        2      Bob   West  Gadget       5.0   15.0
2        3  Charlie   East  Widget       8.0    2.5
3        4    Alice   East   Gizmo       3.0    7.0
4        5     Dave  South  Widget       NaN    2.5
5        6      Bob   West  Gadget       7.0   15.0
6        7      Eve  North   Gizmo      12.0    7.0
7        8  Charlie   East  Gadget       4.0   15.0
8        9    Alice   West  Widget       6.0    2.5
9       10     Dave  South   Gizmo       9.0    7.0